/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const FileItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'featured' : IDL.Bool,
  'thumbnailUrl' : IDL.Text,
  'downloadUrl' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'addFile' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'deleteFile' : IDL.Func([IDL.Nat], [], []),
  'getFeatured' : IDL.Func([], [IDL.Vec(FileItem)], ['query']),
  'getFiles' : IDL.Func([], [IDL.Vec(FileItem)], ['query']),
  'getFilesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(FileItem)], ['query']),
  'getNotice' : IDL.Func([], [IDL.Text], ['query']),
  'seedData' : IDL.Func([], [], []),
  'setFeatured' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'setNotice' : IDL.Func([IDL.Text], [], []),
  'updateFile' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'verifyAccessPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const FileItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'featured' : IDL.Bool,
    'thumbnailUrl' : IDL.Text,
    'downloadUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'addFile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteFile' : IDL.Func([IDL.Nat], [], []),
    'getFeatured' : IDL.Func([], [IDL.Vec(FileItem)], ['query']),
    'getFiles' : IDL.Func([], [IDL.Vec(FileItem)], ['query']),
    'getFilesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(FileItem)], ['query']),
    'getNotice' : IDL.Func([], [IDL.Text], ['query']),
    'seedData' : IDL.Func([], [], []),
    'setFeatured' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'setNotice' : IDL.Func([IDL.Text], [], []),
    'updateFile' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'verifyAccessPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'verifyAdminPassword' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };